### ISSUE TITLE
Allow users to provide an alternate toml config

### ISSUE THREAD

**Issue by BPHarris** [SuadeLabs/rattr#34]
The current functionality is either that there is no toml config or the config used is the root config, but we ought to allow an override like so:

```bash
rattr --config /tmp/blah.toml /tmp/file.py
```

**Comment by habospace** [comment]
Should be easy, just try to obtain the path from the "--config" arg on this line: https://github.com/SuadeLabs/rattr/blob/main/rattr/cli/parser.py#L156 and use that path instead of trying to find project default .toml file.
